font: JetBrains Mono 15
background: "#060321"
color: "#bbbbbb"
border: "#888888"
separator: " : "
border_width: 0
corner_r: 0
padding: 5
rows_per_column: 5
anchor: bottom
margin_bottom: 200

menu:
  # Applications
  # Quick actions
  - key: .
    desc: Spotlight
    cmd: noctalia-shell ipc call launcher toggle
  - key: " "
    desc: Spotlight
    cmd: noctalia-shell ipc call launcher toggle

  - key: t
    desc: Terminal
    cmd: wezterm

  - key: T
    desc: TerminalDumb
    cmd: foot

  - key: s
    desc: Browser
    cmd: librewolf

  - key: e
    desc: Browser
    cmd: emacsclient

  - key: a
    desc: AI
    submenu:
      - key: f
        desc: Files
        cmd: nautilus

  # Window management
  - key: n
    desc: Niri
    submenu:
      - key: v
        desc: Float
        cmd: niri msg action toggle-window-floating


  # Power menu
  - key: q
    desc: Power
    submenu:
      - key: s
        desc: Suspend
        cmd: systemctl suspend
      - key: r
        desc: Reboot
        cmd: systemctl reboot
      - key: q
        desc: Shutdown
        cmd: systemctl poweroff

  # Screenshots
  - key: s
    desc: Screenshot
    submenu:
      - key: y
        desc: Full screen
        cmd: grim ~/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png
      - key: s
        desc: Full screen
        cmd: grim ~/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png
      - key: r
        desc: Region
        cmd: grim -g "$(slurp)" ~/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png
      - key: w
        desc: Window
        cmd: grim -g "$(slurp -o)" ~/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png


  - key: c
    desc: Clipboard
    cmd: wl-paste
  - key: "?"
    desc: Help
    cmd: foot -e sh -c "cat ~/.config/wlr-which-key/config.yaml | less"
