# Generated by nixos-generate-config for ThinkPad X1 Extreme Gen1
# Manual edits for NVIDIA GPU and k3s optimizations
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  # Boot configuration for X1 Extreme Gen1
  boot.initrd.availableKernelModules = [ 
    "xhci_pci"      # USB 3.0
    "nvme"          # NVMe SSD
    "usb_storage"   # USB storage
    "sd_mod"        # SD cards
    "rtsx_pci_sdmmc" # Realtek SD card reader
    "ahci"          # SATA controller
    "thunderbolt"   # Thunderbolt support
  ];
  
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ 
    "kvm-intel"     # Intel virtualization
    "nvidia"        # NVIDIA GPU
    "nvidia_modeset"
    "nvidia_uvm"
    "nvidia_drm"
  ];
  
  boot.extraModulePackages = [ 
    config.boot.kernelPackages.nvidia_x11
  ];

  # Filesystems - managed by disko during install
  fileSystems."/" = lib.mkDefault {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = lib.mkDefault {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  swapDevices = [ ];

  # Networking - Intel Ethernet and WiFi
  networking.useDHCP = lib.mkDefault true;

  # Platform
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
